### ISSUE TITLE
When link of project page is sent via IM service, the preview doesn't show the API part of APINF icon

### ISSUE THREAD

**Issue by Nazarah** [apinf/apinf.github.io#10]
This is due to using the white logo

Facebook Messenger
![15224724_10154469654228387_1437439670_o](https://cloud.githubusercontent.com/assets/17976243/20710623/f5a229a2-b643-11e6-93d0-11a9b6ad1e3a.jpg)

Viber
![15303830_10154469654028387_443502158_o](https://cloud.githubusercontent.com/assets/17976243/20710644/074afda0-b644-11e6-8e7a-7eab03e46f6c.jpg)

**Comment by preriasusi** [comment]
Very minor at the moment.
