### ISSUE TITLE
In Project page, the section name on topbar that is in current view doesn't get highlighted. Instead the name of the previous section gets highlighted.

### ISSUE THREAD

**Issue by Nazarah** [apinf/apinf.github.io#13]
e.g. If we are viewing Open Source section, the name Service gets highlighted.
![projectpage](https://cloud.githubusercontent.com/assets/17976243/20969060/00ac3534-bc90-11e6-8817-ecc14719a42f.gif)

**Comment by nnn** [comment]
Already fixed with https://github.com/apinf/apinf.github.io/pull/11
