### ISSUE TITLE
Implement continuous deployment 

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/apinf.github.io#19]
Just like https://github.com/apinf/docs/issues/60, why not setting up travis to deploy page modifications automatically?

**Comment by mauriciovieira** [comment]
@brylie can you give me admin access here, too?

**Comment by brylie** [comment]
Done.

**Comment by mauriciovieira** [comment]
@bajiat, I tried and could not build locally the site using `hugo` because the `contents` directory is missing. 

As you said, a new website is being built. So I can help automating the publishing if needed, then.

Closing this task by now.
