### ISSUE TITLE
Add deployment instructions

### ISSUE THREAD

**Issue by brylie** [apinf/apinf.github.io#8]
In order for other members of our team to be able to deploy website changes, add deployment instructions to README.

# Definition of done
* [ ] Create a method for automatic deployment to the new VM.
* [ ] Document the deployment instructions.

**Comment by bajiat** [comment]
@nnn You're basically the only one who could do this. Please estimate.

**Comment by nnn** [comment]
Basically at the moment there is no automatic deployment process. I am aware that's part of the definition of done, just wondering if should I go for it this Sprint.
Right now I have just manually uploaded all static files from develop to the VM, of course this is a temp solution and looks rather ugly, but that was high-priority and urgent task, so we decided to go for it.

Website is powered by [Hugo](https://gohugo.io/).
At the moment we store Hugo related code in develop and generated site in master branch.

**Comment by brylie** [comment]
The text instructions are fine for now. We don't change the site that often currently, so probably don't need 'continuous integration'.
